---

- name: users > Template config
  template:
    src:  "{{ manala_proftpd_users_template|ternary(manala_proftpd_users_template, 'users/default.j2') }}"
    dest: "{{ manala_proftpd_users_file }}"
    mode: 0600

- name: users > home directories
  file:
    path: "{{ item.home }}"
    owner: manala_proftpd_users_default_uid
    group: manala_proftpd_users_default_gid
    mode: 0600
    state: directory
  with_items: "{{ manala_proftpd_users }}"
